---
- name: add project user profile
  template: src=profile.j2 dest=/projects/{{project_name}}/.profile
- name: add project user bashrc
  template: src=bashrc.j2 dest=/projects/{{project_name}}/.bashrc
- name: migrate
  command: /projects/{{project_name}}/virt/bin/python manage.py migrate chdir=/projects/{{project_name}}/src/thezombies
  environment: django_environment