---
- name: install rabbitmq
  apt: name=rabbitmq-server update_cache=yes
- name: write rabbitmq-server config
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify:
    - restart rabbitmq

