---
- name: Set up www.thezombies
  hosts: thezombies-site
  user: ubuntu
  sudo: yes
  roles:
    - role: common-roles/common
      hostname: thezombies.org
      extra_packages:
        - libpq-dev
        - yajl-tools
    - role: common-roles/django
      project_name: thezombies
      python_version: 2
      git_repositories:
          - repo: "git://github.com/sunlightlabs/thezombies.git"
            dir: thezombies
      wsgi_module: thezombies.wsgi:application
    - role: thezombies
      project_name: thezombies
    - role: project-user
      project_name: thezombies

