---
- name: Set up workers.thezombies
  hosts: thezombies-workers
  user: ubuntu
  sudo: yes
  roles:
    - role: common-roles/common
      extra_packages:
        - libpq-dev
    - role: celery-django
      project_name: thezombies
      python_version: 2
      git_repositories:
          - repo: "git://github.com/sunlightlabs/thezombies.git"
            dir: thezombies
